version: '3.4'

services:
  vincia.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vincia-api
    restart: always
    environment: 
      API_ENVIRONMENT: "PRODUCTION"
    ports:
      - 8080:8080
    dns:
      - 8.8.8.8
